steps:
# frontend deployment
# Step 1: For installing dependencies
  - name: "gcr.io/cloud-builders/npm"
    id: Install
    args: ["install"]

# Step 2: For creating optinimized build
  - name: "gcr.io/cloud-builders/npm"
    id: Build
    args: ["run", "build"]

# Step 3: This step will execute app.yaml in your folder and deploy your app based on the configuration specified
  - name: "gcr.io/cloud-builders/gcloud"
    id: Deploy
    entrypoint: "bash"
    args:
      - -c
      - |
        if [ $BRANCH_NAME == 'develop' ]
        then
          echo "Branch = $BRANCH_NAME" && gcloud app deploy
        fi
        
        if [ $BRANCH_NAME == 'master' ]
        then
          echo "Branch = $BRANCH_NAME" && gcloud app deploy
        fi
# timeout specified for this step as deployment may take more that default time(10min)
    timeout: "30m0s" 
